#imagen
FROM tomcat:lastest
#copiar y descomprimir el .war de nuestra aplicacion en webapps de tomcat en el contenedor
COPY aplicacion.war /usr/local/tomcat/webapps/

#HAY QUE LLAMAR AL FOKIN .WAR aplicacion PARA QUE FUNCIONE